# Generated by Django 5.2 on 2025-04-22 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driveregistration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bloodinventory',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='registration_date',
        ),
        migrations.AlterField(
            model_name='bloodinventory',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='donationdrive',
            name='contact_person',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donationdrive',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donationdrive',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donationdrive',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donationdrive',
            name='organizer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donationdrive',
            name='registered_donors',
            field=models.ManyToManyField(related_name='donation_drives', through='donation.DriveRegistration', to='donation.donor'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='driveregistration',
            name='registration_date',
        ),
    ]
