# Generated by Django 5.2 on 2025-04-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_driveregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationdrive',
            name='eligibility_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='map_embed',
            field=models.TextField(blank=True, help_text='Embed code or URL for map/directions'),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='preparation_tips',
            field=models.TextField(blank=True),
        ),
    ]
