# Generated by Django 5.2 on 2025-04-22 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_donationdrive_eligibility_requirements_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driveregistration',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='driveregistration',
            name='donor',
        ),
        migrations.AlterModelOptions(
            name='bloodinventory',
            options={'ordering': ['expiry_date', 'blood_type', 'component']},
        ),
        migrations.RenameField(
            model_name='bloodinventory',
            old_name='units_available',
            new_name='units',
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='component',
            field=models.CharField(choices=[('RBC', 'Red Blood Cells'), ('PLT', 'Platelets'), ('PLA', 'Plasma')], default='RBC', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='critical_level',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='expiry_date',
            field=models.DateField(default='2024-12-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bloodinventory',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='bloodinventory',
            unique_together={('blood_type', 'component', 'expiry_date')},
        ),
        migrations.DeleteModel(
            name='DonationDrive',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.DeleteModel(
            name='DriveRegistration',
        ),
    ]
