# Generated by Django 5.2 on 2025-04-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_donationdrive_donor_driveregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationdrive',
            name='max_donors',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
