# Generated by Django 5.2 on 2025-04-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_merge'),
        ('donation', '0007_merge_20250422_2135'),
    ]

    operations = [
    ]
