# Generated by Django 5.2 on 2025-04-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_merge_0007_merge_0007_merge_20250422_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='health_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
