# Generated by Django 5.2 on 2025-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_donor_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='health_info',
        ),
        migrations.AddField(
            model_name='donor',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='chronic_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='deferral_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_deferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_hemoglobin_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='medications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
