# Generated by Django 5.2 on 2025-04-23 00:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_donor_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='emergency_contact_relation',
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
    ]
