# Generated by Django 5.2 on 2025-04-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0010_add_emergency_contact_relation'),
        ('donation', '0010_remove_donor_health_info_donor_allergies_and_more'),
    ]

    operations = [
    ]
