# Generated by Django 5.2 on 2025-04-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0011_merge_20250422_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='eligibility_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_screening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
