# Generated by Django 5.2 on 2025-04-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0012_donor_eligibility_status_donor_last_screening_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='health_info',
            field=models.TextField(blank=True),
        ),
    ]
