# Generated by Django 5.2.1 on 2025-05-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0013_donor_health_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='bloodinventory',
            name='component',
            field=models.CharField(choices=[('WB', 'Whole Blood'), ('PLS', 'Plasma'), ('PLT', 'Platelets'), ('RBC', 'Red Blood Cells')], max_length=3),
        ),
        migrations.AlterField(
            model_name='bloodinventory',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
