# Generated by Django 5.2.1 on 2025-05-21 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0014_donor_gender_alter_bloodinventory_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationdrive',
            name='blood_type_targets',
            field=models.JSONField(blank=True, default=dict, help_text='Target number of donors for each blood type'),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='contact_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='contact_person',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='emergency_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='equipment_available',
            field=models.TextField(default='', help_text='Available medical equipment and supplies'),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='max_donors_per_slot',
            field=models.PositiveIntegerField(default=2, help_text='Maximum donors that can be processed simultaneously'),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='medical_staff_count',
            field=models.PositiveIntegerField(default=2, help_text='Number of medical staff available'),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='pre_donation_instructions',
            field=models.TextField(default='', help_text='Instructions for donors to follow before donation'),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='required_documents',
            field=models.TextField(default='', help_text='List of required documents donors should bring'),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='safety_protocols',
            field=models.TextField(default='', help_text='COVID-19 and other safety protocols'),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='venue_details',
            field=models.TextField(blank=True, help_text='Specific details about the venue, parking, etc.'),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='weather_dependent',
            field=models.BooleanField(default=True, help_text='Whether the drive may be affected by weather'),
        ),
        migrations.AddField(
            model_name='driveregistration',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driveregistration',
            name='blood_pressure',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='driveregistration',
            name='confirmed_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveregistration',
            name='donation_completed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driveregistration',
            name='donation_started',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driveregistration',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveregistration',
            name='hemoglobin_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='driveregistration',
            name='post_donation_condition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='driveregistration',
            name='pre_screening_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveregistration',
            name='pre_screening_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driveregistration',
            name='pulse_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driveregistration',
            name='recovery_time',
            field=models.PositiveIntegerField(blank=True, help_text='Recovery time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='driveregistration',
            name='registration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='driveregistration',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driveregistration',
            name='units_collected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='donationdrive',
            name='eligibility_requirements',
            field=models.TextField(default='', help_text='Basic eligibility criteria for donors'),
        ),
        migrations.AlterField(
            model_name='driveregistration',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
