# Generated by Django 5.2.1 on 2025-05-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0015_donationdrive_blood_type_targets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationdrive',
            name='blood_type_targets',
            field=models.JSONField(blank=True, default=dict, help_text='Target number of donors for each blood type', null=True),
        ),
    ]
