# Generated by Django 5.2.1 on 2025-05-22 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0016_alter_donationdrive_blood_type_targets'),
    ]

    operations = [
    ]
