# Generated by Django 5.2.1 on 2025-05-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0017_auto_20250522_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationdrive',
            name='date',
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='end_date',
            field=models.DateField(help_text='End date of the donation drive', null=True),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='start_date',
            field=models.DateField(help_text='Start date of the donation drive', null=True),
        ),
    ]
