# Generated by Django 5.2.1 on 2025-05-22 02:36

from django.db import migrations
from django.utils import timezone

def populate_date_fields(apps, schema_editor):
    DonationDrive = apps.get_model('donation', 'DonationDrive')
    today = timezone.now().date()
    
    # Update all existing records
    for drive in DonationDrive.objects.all():
        if not drive.start_date:
            drive.start_date = today
            drive.end_date = today
            drive.save()

class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0018_remove_donationdrive_date_donationdrive_end_date_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_date_fields),
    ] 